### ISSUE TITLE
Deleting 2 messages in a row

### ISSUE THREAD

**Issue by m707** [wshanks/tbkeys#104]
I have mapped 'd' to the command delete messages this way:

    "d": "window.goDoCommand('cmd_delete')",

but everytime I hit d the highlighted message and it's follower are deleted, so two messages in a row. 

Using tbkeys 2.2.0 addon for TB 91.10.0 (64-Bit) on Debian bullseye.

**Comment by wshanks** [comment]
Strange, I can't reproduce this, but it is obviously terrible behavior. Does it still happen if you make `d` your only binding? You could also try using `cmd:cmd_delete` instead of `window.goDoCommand('cmd_delete')`.

**Comment by m707** [comment]
Issue fixed by cmd:cmd_delete. THX and sorry for the late reply.
