### ISSUE TITLE
Shortcut to Open Unified INBOX 

### ISSUE THREAD

**Issue by thisisbenwoo** [wshanks/tbkeys#107]
Hello,

I've searched through the Issues here, and I was glad to have found [Issue 72](https://github.com/wshanks/tbkeys/issues/72#issuecomment-1005517292) that answered a number of my questions. I'm trying to emulate the GMAIL keys, and one of them that I really like is typing G followed by I to go to the INBOX. In the same Issue, I found the following reference:

` "g i": "window.gFolderTreeView.selectFolder(window.MailUtils.getExistingFolder('imap://account@domain.tld/INBOX'), true);",`

I think this will be the right command, however, what I want is to open the **Unified INBOX**. Does tbkeys support this please? If so, what should the URL be for the ExistingFolder name?

Thank you in advance.

Ben

**Comment by thisisbenwoo** [comment]
Thank you @morat523035 for your answer. I tried the command I quoted with your URL, but it doesn't seem to work. I think I need to use the `cmd_goFolder` command and do something like:

`"g i" : "cmd:cmd_goFolder **[SOMETHING SOMETHING SOMETHING]**",`

But I am too new to Thunderbird to understand how to construct that command. I'm already out of my depth. So thanks again in advance to anyone who can help.

ben

**Comment by morat523035** [comment]
Are you using tbkey or tbkeys-lite?

You cannot run arbitrary javascript with tbkeys-lite.

You can use the cmd shorthand and func shorthand with tbkeys and tbkeys-lite.

Use the cmd shorthand for calling a command using the goDoCommand method.

For example, "cmd:cmd_nextMsg" is the same as "window.goDoCommand('cmd_nextMsg');".

Use the func shorthand for calling a function on the window object without a parameter.

For example, "func:MsgNewMessage" is the same as "window.MsgNewMessage();".

There is a tbkeys.xpi link on the releases page.

[http://github.com/wshanks/tbkeys#install](https://github.com/wshanks/tbkeys#install)

**Comment by thisisbenwoo** [comment]
I'm using tbkeys-lite. I installed it through the Add-Ons section of settings. I have recreated most of the Gmail shortcut keys based on the examples in the default keybindings. So far I have ...
```
{
    "o": "cmd:cmd_openMessage",
    "f": "cmd:cmd_forward",
    "#": "cmd:cmd_delete",
    "r": "cmd:cmd_reply",
    "A": "cmd:cmd_replyall",
    "e": "cmd:cmd_archive",
    "I": "cmd:cmd_markAsRead",
    "!": "cmd:cmd_markAsJunk",
    "c": "func:MsgNewMessage",
    "u": "tbkeys:closeMessageAndRefresh"
}

```
The **G**o to **I**nbox (specifically, I want to go to the Unified Inbox) by typing G then I is the last shortcut I want to recreate, and this is where I'm running into a problem. My previous email client was Mailbird, and I got spoilt that Mailbird uses Gmail's shortcuts for their shortcuts. 

Based on what you're saying, I'm not sure I fully understand whether I can use the goFolder function with the Unified Inbox as a parameter? If so, how would that look like? Or does the go to Unified Inbox "function" require JavaScript? I don't mind JS, but I'd rather not do it simply because I don't want to chew up system resources just to go to the Inbox. I'm not THAT lazy! 

However, if tbkeys (pro?) can provide the necessary functions, then I'm more than happy to look at it and pay for it. (Can't be as expensive as Mailbird is!)

Thanks again.

**Comment by morat523035** [comment]
Try the following command with tbkeys. That works for me.

```
window.gFolderTreeView.selectFolder(window.MailUtils.getExistingFolder('mailbox://nobody@smart%20mailboxes/Inbox'));
```

The cmd_goFolder command uses the event.target object to figure out the folder the user clicked in the Menu Bar > Go > Folder menu popup. It isn't a usable command for tbkeys or tbkeys-lite since it depends on the target element when triggered.

Reference
http://searchfox.org/comm-esr102/search?q=cmd_goFolder

tbkeys and tbkeys-lite are both free.

More info on diff between tbkeys and tbkeys-lite
http://github.com/wshanks/tbkeys#readme

**Comment by thisisbenwoo** [comment]
Thanks @morat523035 . 
I'm still a little way off from fully understanding how to implement this. But I really appreciate the direction. I'll have to do a bit more learning. Thank you again.

**Comment by thisisbenwoo** [comment]
Follow .Up ...
I installed tbkeys.xpi and got it to work with:
`"g i": "window.gFolderTreeView.selectFolder(window.MailUtils.getExistingFolder('mailbox://nobody@smart%20mailboxes/Inbox'));",`

Thank you,

**Comment by thisisbenwoo** [comment]
You are correct that in the latest version of Thunderbird 115, it doesn't work. I noticed it a couple of versions ago, but I have been too busy to report it (I'm sorry). 

It'll be next week (at the earliest) before I can get to play with this. In the meantime, I have not changed my settings, so, my tbkeys config is still:


```
{
    "f": "cmd:cmd_forward",
    "r": "cmd:cmd_reply",
    "A": "cmd:cmd_replyall",
    "a": "cmd:cmd_replyall",
    "e": "cmd:cmd_archive",
    "I": "cmd:cmd_markAsRead",
    "c": "func:MsgNewMessage",
    "]": "cmd:cmd_toggleFolderPane",
    "g i": "window.gFolderTreeView.selectFolder(window.MailUtils.getExistingFolder('mailbox://nobody@smart%20mailboxes/Inbox'));",
    "ctrl+q": "window.goQuitApplication(window.event)"
}
```

Everything works except for the G I combo.

**Comment by morat523035** [comment]
Try this:

```
// Thunderbird 102
window.gFolderTreeView.selectFolder(window.GetFirstSelectedMsgFolder().rootFolder);

// Thunderbird 115
window.gTabmail.tabInfo[0].folder = window.GetFirstSelectedMsgFolder().rootFolder;
```

Is gFolderTreeView not available anymore in TB113?
http://thunderbird.topicbox.com/groups/addons/T48deff5d86abce14-M71b7848a4707dd106e82ed38

**Comment by thisisbenwoo** [comment]
> Try this:
> 
> ```
> // Thunderbird 102
> window.gFolderTreeView.selectFolder(window.GetFirstSelectedMsgFolder().rootFolder);
> 
> // Thunderbird 115
> window.gTabmail.tabInfo[0].folder = window.GetFirstSelectedMsgFolder().rootFolder;
> ```
> 
> Is gFolderTreeView not available anymore in TB113? http://thunderbird.topicbox.com/groups/addons/T48deff5d86abce14-M71b7848a4707dd106e82ed38

I just tried replacing 

```
"g i": "window.gFolderTreeView.selectFolder(window.MailUtils.getExistingFolder('mailbox://nobody@smart%20mailboxes/Inbox'));",
```
with
```
"g i": "window.gTabmail.tabInfo[0].folder = window.GetFirstSelectedMsgFolder().rootFolder;",
```

and the result is the "Welcome" page for the specific mailbox in which I was last. So, if I were in mailbox A's sent box, then it would go to the "welcome page" for mailbox A, and not the Unified Inbox.

![image](https://github.com/wshanks/tbkeys/assets/45885373/56d89dcc-5175-4198-8712-914e81ee96ce)

**Comment by morat523035** [comment]
@thisisbenwoo

```
// Thunderbird 102
window.gFolderTreeView.selectFolder(window.MailUtils.getExistingFolder('mailbox://nobody@smart%20mailboxes/Inbox'));

// Thunderbird 115
window.gTabmail.tabInfo[0].folder = window.MailUtils.getExistingFolder('mailbox://nobody@smart%20mailboxes/Inbox');
```

**Comment by thisisbenwoo** [comment]
👍🏻
