### ISSUE TITLE
Settings lost after TB update - how can I restore tbkeys settings from a profile backup?

### ISSUE THREAD

**Issue by spi43984** [wshanks/tbkeys#111]
After updating my TB to 102 my tbkeys settings got screwed. I'd like to restore them from my TB profile folder backups. But I don't want to restore the entire folder (as I would need to downgrade TB first), just pull the tbkeys settings from the appropriate config file.

I see that tbkeys uses browser.storage.local.set to load/store its settings - in what file are the settings finally stored and how can I dump the settings to copy&paste them back into tbkeys?

**Comment by morat523035** [comment]
The data is stored compressed.

More info
http://stackoverflow.com/questions/65448110
http://stackoverflow.com/questions/54920939

The UUID is different in every browser profile instance.

Menu Bar > Tools > Developer Tools > Debug Addons > tbkeys > UUID

**Comment by spi43984** [comment]
> The data is stored compressed in the sqlite file.
> 
> More info http://stackoverflow.com/questions/65448110 http://stackoverflow.com/questions/54920939
> 
> Location:
> 
> `<profile folder>\storage\default\moz-extension+++<UUID>^userContextId=4294967295\idb\3647222921wleabcEoxlt-eengsairo.sqlite`
> 
> The UUID is different in every browser profile instance.
> 
> Menu Bar > Tools > Developer Tools > Debug Addons > tbkeys > UUID

Excellent. That works. Many thx!

To sum it up for others:

1. Here's a tool to dump the DB the tbkeys settings are stored in: [
moz-idb-edit](https://gitlab.com/ntninja/moz-idb-edit)
2. The DB itself is stored in the TB profile folder under storage/default/'moz-extension+++${EXT_UUID}^userContextId=1234567890' - just in case you need to restore data from backup. The UUID you see either in prefs.js (search for 'tbkeys-lite@addons.thunderbird.net', the UUID is the one right after or as @morat523035 wrote debug the addon and check for the UUID.
3. The addon's ID 'tbkeys-lite@addons.thunderbird.net' is needed as input for the script.
4. Run the script with `./moz-idb-edit --extension "tbkeys-lite@addons.thunderbird.net" --profile "<your TB profile folder>" "mainkeys"`.
