### ISSUE TITLE
Shortcut for "View->Message Body As->All Body Parts"?

### ISSUE THREAD

**Issue by salzrat** [wshanks/tbkeys#112]
Is there a way to add a shortcut for "View->Message Body As->All Body Parts" and "View->Message Body As->Original HTML"?
Thanks!

**Comment by morat523035** [comment]
Try these commands:

`func:MsgBodyAllParts`
`func:MsgBodyAllowHTML`

You need to set the mailnews.display.show_all_body_parts_menu preference to true to show the "All Body Parts" menu item.

Tips
http://forums.mozillazine.org/viewtopic.php?p=14872763#p14872763

**Comment by salzrat** [comment]
Thanks, perfect!
