### ISSUE TITLE
Command to quit app

### ISSUE THREAD

**Issue by thisisbenwoo** [wshanks/tbkeys#113]
Hello, 
I'm sure this question has been asked before, but I cannot find any reference to it. My question is (hopefully) simple:

I want to map Ctrl-Q to close Thunderbird. Can someone point me to the right code. I've tried what I can find on the Keyconfig forums, but no luck. 

Thanks in advance

**Comment by morat523035** [comment]
You can use the following code to easily extract a command using the error console. The trick does not work for all user interface elements.

```
function getCommand(event) {
  window.removeEventListener("command", getCommand, true);
  event.preventDefault();
  event.stopPropagation();
  alert(event.originalTarget.getAttribute("oncommand") ||
    event.originalTarget.getAttribute("onclick"));
}
window.addEventListener("command", getCommand, true);
```

Extract the Menu Bar > File > Exit command:

* run code in error console
* left click "File" menu in Menu Bar
* left click "Exit" menu item

`window.goQuitApplication(window.event);`

Tips
http://forums.mozillazine.org/viewtopic.php?f=48&t=72994&start=3480

**Comment by thisisbenwoo** [comment]
@morat523035 
That's great. It worked! The problem is that it only works when I define it as "q", but when I tried to make it "ctrl+Q", it didn't do anything:
```
"ctrl+Q": "window.goQuitApplication(window.event)"
```
This is the last command thus, no **,** at the end.
I followed the [Mousetrap](https://craig.is/killing/mice) examples

Thanks a lot, now I know how to do so much more with tbkeys!

**Comment by thisisbenwoo** [comment]
@morat523035 thanks for the amazingly quick response. Worked perfectly!

**Comment by Cleversn** [comment]
How can I discover the complete path to a command or function?

For example: I wanted to make a key to go to the next unread message, then I opened the error console and ran the code presented here. It gave me goDoCommand(cmd_nextUnreadMsg), but it didn't work until I guessed I had to put window. in front of it.

Now I want to make a key to CloseTabOrWindow(); but it doesn't work, even when I put something in front of it like window. or func:

**Comment by morat523035** [comment]
@Cleversn 

The code snippet works here.

* Run code in error console, Menu Bar > Go > Next > Unread Message
* Open tab, Run code in error console, Menu Bar > File > Close

Try these:

`window.goDoCommand('cmd_nextUnreadMsg');`
`window.CloseTabOrWindow();`

I tested the commands. They work for me.

**Comment by Cleversn** [comment]
Thanks much, Morat. I assigned it to the esc key, which for some reason doesn't work when the focus is in certain parts of a tab. Now it's working.
