### ISSUE TITLE
Alt-F in Inbox Tab opens a forward message window rather than opening File menu

### ISSUE THREAD

**Issue by thisisbenwoo** [wshanks/tbkeys#114]
When I'm in the Inbox tab, with an email selected, when I enter Alt-F, it opens a forward message window. This is not a mapped key in tbkeys (I'm using tbkeys, not tbkeys-lite) but I also tried tbkeys-lite, and it has the same effect. I checked the Thunderbird [shortcut keys page](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-thunderbird), and forwarding an email is Ctrl-L, so I don't know why Alt-F opens a forward message window, rather than selecting the File menu.

I've tried disabling all extensions except for tbkeys - same result. 
When I click Restore Defaults then Save Settings, the problem still exists.
When I click Unset Singles then Save Settings, the problem still exists.
But when I disable tbkeys, it works the way it's supposed to.

My config is below:
```
{
    "j": "cmd:cmd_nextMsg",
    "k": "cmd:cmd_previousMsg",
    "o": "cmd:cmd_openMessage",
    "f": "cmd:cmd_forward",
    "#": "cmd:cmd_delete",
    "r": "cmd:cmd_reply",
    "A": "cmd:cmd_replyall",
    "e": "cmd:cmd_archive",
    "I": "cmd:cmd_markAsRead",
    "!": "cmd:cmd_markAsJunk",
    "c": "func:MsgNewMessage",
    "g i": "window.gFolderTreeView.selectFolder(window.MailUtils.getExistingFolder('mailbox://nobody@smart%20mailboxes/Inbox'));",
    "u": "tbkeys:closeMessageAndRefresh"
}
```

Thoughts anyone? 
Thanks in advance

**Comment by morat523035** [comment]
I can reproduce the issue using Alt (hold) F with the following config. However, Alt (release) F works correctly.

```
{
  "f": "window.alert('test');"
}
```

I can workaround the issue using Alt (hold) F with the following config.

```
{
  "f": "window.alert('test');",
  "alt+f": "window.document.getElementById('menu_FilePopup').openPopup();"
}
```

Similar issue
http://github.com/wshanks/tbkeys/issues/78#issuecomment-1088818894

**Comment by thisisbenwoo** [comment]
Thank you. It worked perfectly.
I'll mark this as solved, but I'm wondering if this is a bug or a feature?
