### ISSUE TITLE
How to trigger a menu item?

### ISSUE THREAD

**Issue by kp-gl** [wshanks/tbkeys#122]
Is it possible to trigger a menu item (like in mail composition: Format->Align->Left) with this add-on?
I searched on the info page for 'menu' and the command [list](https://hg.mozilla.org/comm-central/file/tip/mail/base/content/mainCommandSet.inc.xhtml) about this - but found nothing.
Thanks a lot in advance!

**Comment by morat523035** [comment]
Try these:

`
window.doStatefulCommand('cmd_align', 'left');
`
`
window.doStatefulCommand('cmd_align', 'center');
`
`
window.doStatefulCommand('cmd_align', 'right');
`
`
window.doStatefulCommand('cmd_align', 'justify');
`

Reference
http://searchfox.org/comm-esr102/search?q=cmd_align

**Comment by kp-gl** [comment]
Thanks a lot morat523035, but tbh I am not aware how to put your suggestion into the bindings scheme
Like "j": "cmd:cmd_nextMsg",

**Comment by kp-gl** [comment]
Solved, thanks a lot!
