### ISSUE TITLE
Question: (How) can I simulate a modfier + key with a tbkeys single key shortcut?

### ISSUE THREAD

**Issue by yaddablah** [wshanks/tbkeys#125]
Maximize Message Pane extension required a modifier + key as a shortcut (e.g. control+m). I'd like to use tbkeys so a single key simulates this "modifier + key" keypress.

That is:

"m": "some command/code to simulate control+m"

**Comment by morat523035** [comment]
MailExtension API support
http://github.com/wshanks/tbkeys/issues/46

mozillaZine post about Maximize Message Pane and tbkeys
https://forums.mozillazine.org/viewtopic.php?p=14922347#p14922347

You cannot run arbitrary javascript like in the mozillaZine post with tbkeys-lite.

There is a tbkeys.xpi link on the releases page.

Install
http://github.com/wshanks/tbkeys#install

Tips
https://forums.mozillazine.org/viewtopic.php?p=14872763#p14872763

**Comment by yaddablah** [comment]
Thanks for the details morat.

The "mozillaZine post"  didn't work. It may or may not be because I'm on Thunderbird 78.14.0. I am using tbkeys (not lite).

It's more generic if I'm able to simulate a modified key press. I should then be able to make almost any keyboard shortcut into a single key press.

One thing I learned from the tips URL is how to access a menu item. Thanks! Samples below for future readers:

"a": "window.document.getElementsByAttribute('label', 'All Body Parts')[0].doCommand();",

"s": "window.document.getElementsByAttribute('label', 'Simple HTML')[0].doCommand();"

**Comment by morat523035** [comment]
The 4 code snippets in the mozillaZine post work for me using the error console.

Maximize Message Pane 2.1.1
Thunderbird 102.7.0
Windows 10 Pro 21H2 32-bit

I don't know how to simulate a keypress event. I believe the developers made it harder to do that for security reasons. The nsIDOMWindowUtils.sendKeyEvent method doesn't work anymore.

nsIDOMWindowUtils.sendKeyEvent method
http://forums.mozillazine.org/viewtopic.php?p=14219597#p14219597

**Comment by morat523035** [comment]
Try the nsIDOMWindowUtils.sendNativeKeyEvent method.

e.g. synthesize Shift+F8 to maximize message pane

```
(function () {
  var KEYBOARD_LAYOUT_EN_US = {name: 'US', Mac: 0, Win: 0x00000409, hasAltGrOnWin: false};
  var WIN_VK_F8 = 0x00420077;
  var NATIVE_MODIFIER_SHIFT_LEFT = 0x00000100;
  window.windowUtils.sendNativeKeyEvent(KEYBOARD_LAYOUT_EN_US, WIN_VK_F8, NATIVE_MODIFIER_SHIFT_LEFT, '', '');
})();
```

Reference
http://searchfox.org/mozilla-esr102/search?q=KEYBOARD_LAYOUT_EN_US
http://searchfox.org/mozilla-esr102/search?q=WIN_VK_F8
http://searchfox.org/mozilla-esr102/search?q=NATIVE_MODIFIER_SHIFT_LEFT
http://searchfox.org/mozilla-esr102/search?q=sendNativeKeyEvent

**Comment by yaddablah** [comment]
Thanks again morat. I couldn't get the the nsIDOMWindowUtils.sendNativeKeyEvent method to work in TB 78.

I was however able to successfully test your original suggestion in Thunderbird 91:

mozillaZine post about Maximize Message Pane and tbkeys
http://forums.mozillazine.org/viewtopic.php?p=14922347#p14922347

Here's the code future readers:

"m": "(function () { var enumerator = window.Services.ww.getWindowEnumerator(); while (enumerator.hasMoreElements()) { var win = enumerator.getNext(); if (win.document && win.document.documentURI == 'chrome://extensions/content/dummy.xhtml') { win.document.querySelectorAll('browser').forEach(function (aBrowser) { var addonPolicy = aBrowser._contentPrincipal.addonPolicy; if (addonPolicy && addonPolicy.extension.manifest.name == 'Maximize Message Pane') { addonPolicy.extension.tabManager.addActiveTabPermission(); addonPolicy.extension.shortcuts.onCommand('cmd_max-msg-pane'); } }); } } })();"

**Comment by morat523035** [comment]
I'm glad you got it working.

I got the nsIDOMWindowUtils.sendNativeKeyEvent method working using the error console.

German users need to use the KEYBOARD_LAYOUT_GERMAN object. Mac users need to use the Mac_VK_ constants.

Other examples
https://forums.mozillazine.org/viewtopic.php?p=14949538#p14949538

**Comment by yaddablah** [comment]
>I'm glad you got it working.

At least I know it's possible in 91. I have reasons to stay on 78 though. I followed your "Other examples" link and was able to create this. It works except that the modifier is ignored ("m" simulates F8 instead of Shift-F8):

"m": "(function () { var KEYBOARD_LAYOUT_EN_US = {name: 'US', Mac: 0, Win: 0x00000409, hasAltGrOnWin: false}; var MAC_VK_F8 = 0x64;; var MAC_VK_Shift = 0x38; var modifiers = 0; modifiers |= MAC_VK_Shift; window.windowUtils.sendNativeKeyEvent(KEYBOARD_LAYOUT_EN_US, MAC_VK_F8, modifiers, '', ''); })();"

**Comment by morat523035** [comment]
I would think the following code snippet is correct on Mac.

```
(function () {
  var KEYBOARD_LAYOUT_EN_US = {name: 'US', Mac: 0, Win: 0x00000409, hasAltGrOnWin: false};
  var MAC_VK_F8 = 0x64;
  var NATIVE_MODIFIER_SHIFT_LEFT = 0x00000100;
  var modifiers = 0;
  modifiers |= NATIVE_MODIFIER_SHIFT_LEFT;
  window.windowUtils.sendNativeKeyEvent(KEYBOARD_LAYOUT_EN_US, MAC_VK_F8, modifiers, '', '');
})();
```

I believe the shift modifier is the same on Mac and Windows.

**Comment by yaddablah** [comment]
That worked. THANKS!

**Comment by yaddablah** [comment]
That worked. THANKS!

Final (working) code snippet:

"m": "(function () { var KEYBOARD_LAYOUT_EN_US = {name: 'US', Mac: 0, Win: 0x00000409, hasAltGrOnWin: false}; var MAC_VK_F8 = 0x64; var NATIVE_MODIFIER_SHIFT_LEFT = 0x00000100; var modifiers = 0; modifiers |= NATIVE_MODIFIER_SHIFT_LEFT; window.windowUtils.sendNativeKeyEvent(KEYBOARD_LAYOUT_EN_US, MAC_VK_F8, modifiers, '', ''); })();"
