### ISSUE TITLE
Add a shortcut to switch the editor type when creating a new message?

### ISSUE THREAD

**Issue by mindinwonderland** [wshanks/tbkeys#137]
Hello, thanks for the wonderful addon!

I have to switch the editor type (HTML or plain text) when writing emails using different accounts. After reading the document, I tried setting the keybindings as follows

```
    ...
    "c": "func:MsgNewMessage",
    "t": "func:MsgNewMessage({shiftKey: true})",
    ...
```
The function `MsgNewMessage({shiftKey: true})` is found in the [old wiki page about Keyconfig](http://kb.mozillazine.org/Keyconfig_extension:_Thunderbird). However, as elaborated in the readme, the command format `func:<func_name>` does not allow any arguments. Thus, the keybinding setting in above does not work.

Is there any way to add this shortcut to switch the default editor type?

**Comment by morat523035** [comment]
You cannot run arbitrary javascript with tbkeys-lite.

You can use the cmd shorthand and func shorthand with tbkeys and tbkeys-lite.

Use the cmd shorthand for calling a command using the goDoCommand method.

For example, "cmd:cmd_nextMsg" is the same as "window.goDoCommand('cmd_nextMsg');".

Use the func shorthand for calling a function on the window object without a parameter.

For example, "func:MsgNewMessage" is the same as "window.MsgNewMessage();".

There is a tbkeys.xpi link on the GitHub releases page.

```
window.MsgNewMessage({shiftKey: true});
```

Similar issue
http://github.com/wshanks/tbkeys/issues/65

**Comment by mindinwonderland** [comment]
Thanks for your reply! Using tbkeys.xpi and `window.MsgNewMessage({shiftKey: true});` works!
