### ISSUE TITLE
Compatibility issue with 115

### ISSUE THREAD

**Issue by thisisbenwoo** [wshanks/tbkeys#140]
Hi, 

I actually use Betterbird, although I don't think this is a Betterbird issue, but Thunderbird. I've upgraded to the beta version of Thunderbird 115. When I type Ctrl-K to do a search, if I type the letter A (lower or upper case), it automatically thinks I'm wanting to Reply-All. So, in reality, I can't search on anything else that has the letter A (or in fact anything that would trigger some sort of message related action). 

I've tried using A, C, E, F, I, J, K, M, R (For me, these are mapped to reflect the G-mail keys, so respectively, Reply All, Compose, Archive, Forward, Mark Read, Next, Previous, Mark Read (this is a standard Thunderbird shortcut), and Reply)

I know that 115 is still in beta, but as I test things I thought I'd drop them in here. Also, I'm not sure if this is a TBkeys things or a Thunderbird 115 thing, but the fact that only keys mapped by TBkeys suggests that it is likely related to TBkeys.

UPDATE1: It seems that if I type using **Shift** and one of the keys above that it _does_ work, **but**, not if I search using the Caps Lock key.
UPDATE2: It seems like UPDATE1 is true except for A and R

Thanks.

b

**Comment by thisisbenwoo** [comment]
@wshanks,
I'd be happy to, but do not know how to? I'm on Windows, I poked around the \Program Files\Betterbird directory then I poked around \Users\me\appdata\Roaming (and Local)\Thunderbird, and don't see a directory called addon. I'm also unfamiliar with what you mean by zip up the contents as a .xpi file.
I'll go to the question in the link and get back to you.

**Comment by thisisbenwoo** [comment]
@wshanks Sorry for the break, getting back to this tomorrow, re: your question [here](https://github.com/wshanks/tbkeys/pull/139#pullrequestreview-1457997423), the short answer is no, but I'll give you a more indepth answer tomorrow.

**Comment by ChauhanT** [comment]
I can confirm this also happens for other fields (like quick-filter).

**Comment by wshanks** [comment]
Feel free to mention anything else besides quick-filter. The search box at least should be fixed now.

**Comment by wshanks** [comment]
The quick filter box was fixed in 2.2.4 (in review queue on addons.thunderbird.net now for tbkeys-lite and released here for plain tbkeys). I will close this for now, but open another issue if you notice another text box capturing keys.

**Comment by ChauhanT** [comment]
Hi @wshanks , thank you for looking into this so quickly! Can't wait for tbkeys-lite to become available on the addons website. Is there any chance you could update this thread when it gets approved ?

**Comment by wshanks** [comment]
@ChauhanT It should be available now.

**Comment by ChauhanT** [comment]
@wshanks Thank you very much for the update and for the info! TB115 feels like it should now!
