### ISSUE TITLE
[Question] End-of-line in composition

### ISSUE THREAD

**Issue by sylowp** [wshanks/tbkeys#141]
Hi,
On macOS I want to bind "ctrl+e" to "end-of-line" in the composition of a message, but I can't find what configuration to use to do so?
Thanks!

**Comment by morat523035** [comment]
Try this:

`cmd:cmd_endLine`

`window.goDoCommand('cmd_endLine');`

Reference
http://searchfox.org/mozilla-esr102/source/dom/base/nsGlobalWindowCommands.cpp
http://searchfox.org/mozilla-esr102/source/dom/events/ShortcutKeyDefinitions.cpp

**Comment by sylowp** [comment]
The first one:
"ctrl+e": "cmd:cmd_endLine"
works perfectly, thanks a lot!
