### ISSUE TITLE
Can one do single key to multiple actions / commands?

### ISSUE THREAD

**Issue by markwmuller** [wshanks/tbkeys#142]
I'd like to bind one key, to two actions (specifically "shift+x" to archive current message, and proceed to previous message). I can't figure out how to do this in tbkeys-lite, can you help? 

Sorry if naïve Q, but I've tried searching through examples, and the mousetrap docs. Most combinations I've tried seem to just fail silently, and of course tbkeys-lite doesn't allow generic functions. 

(great add-on, thank you! I've been wanting more vim-like interaction for ages, this give me that!)

**Comment by morat523035** [comment]
You cannot run arbitrary javascript with tbkeys-lite. There is a tbkeys.xpi link on the GitHub releases page.

Try this:

```window.goDoCommand('cmd_archive'); window.goDoCommand('cmd_previousMsg');```

**Comment by markwmuller** [comment]
Perfect, thank you!
