### ISSUE TITLE
[question] is there a command to enter settings? or even better to enter config editor? 

### ISSUE THREAD

**Issue by pntc** [wshanks/tbkeys#150]
I need shortcut to enter settings or event better to enter config editor but I can't find it. 
Is there any way to open it?

**Comment by morat523035** [comment]
Are you asking for a code snippet to open the config manager?

Try this:

```
(function () {
  var win = window.Services.wm.getMostRecentWindow('mail:3pane');
  var tabmail = win.document.getElementById('tabmail');
  for (var tabInfo of tabmail.tabInfo) {
    var tab = tabmail.getTabForBrowser(tabInfo.browser);
    if (tab?.urlbar?.value == 'about:config') {
      tabmail.switchToTab(tabInfo);
      return;
    }
  }
  tabmail.openTab('contentTab', {url: 'about:config'});
})();
```

You cannot run arbitrary javascript with tbkeys-lite.

There is a tbkeys.xpi link on the GitHub releases page.

Reference
http://searchfox.org/comm-esr115/search?q=showConfigEdit

You can use the config button as an alternative.

Config Button
http://addons.thunderbird.net/thunderbird/addon/987784

**Comment by pntc** [comment]
I'm new to tbkeys so I didn't new I was asking for this but apparently I did ;-) Thank you.

So I 've installed non-lite version, entered settings and in "Main key bindings" I've entered this content:
```
{
    "j": "(function () {
  var win = window.Services.wm.getMostRecentWindow('mail:3pane');
  var tabmail = win.document.getElementById('tabmail');
  for (var tabInfo of tabmail.tabInfo) {
    var tab = tabmail.getTabForBrowser(tabInfo.browser);
    if (tab && tab.urlbar && tab.urlbar.value == 'about:config') {
      tabmail.switchToTab(tabInfo);
      return;
    }
  }
  tabmail.openTab('contentTab', {url: 'about:config'});
})();"
}
```
but it highlights itself wit red color red and I cannot save it. 
What am I missing?

**Comment by morat523035** [comment]
You can test the code snippet using the error console.

Remember to remove the newline characters in custom commands so the input is a valid JSON string.

Troubleshooting
http://forums.mozillazine.org/viewtopic.php?p=14872763#p14872763

Online Multiline to Single Line Converter
http://tools.knowledgewalls.com/online-multiline-to-single-line-converter

**Comment by pntc** [comment]
@morat523035 thank you a lot!
Oneliner solve problem. Also accessing cofing editor helps a lot! Thanks again! 🌞
