### ISSUE TITLE
Focus the message pane in V115

### ISSUE THREAD

**Issue by MatthiasHGW** [wshanks/tbkeys#159]
I used to have the shortcut "y": "func:SetFocusMessagePane" to focus the message pane so that I can scroll through the message text with the cursor keys. This does not work any more with Supernova and I am unable to find the proper command.

Can anyone help me restoring this shortcut?

Thank you - Matthias

**Comment by morat523035** [comment]
Try this:

```
// Thunderbird 102
window.SetFocusThreadPane();

// Thunderbird 115
window.gTabmail.currentAbout3Pane.threadTree.table.body.focus();
```

There isn't a helper function like SetFocusThreadPane in Thunderbird 115.

You cannot run arbitrary javascript with tbkeys-lite. There is a tbkeys.xpi link on the GitHub releases page.

How to focus other panes:

```
// Thunderbird 102
window.document.getElementById("folderTree").focus();

// Thunderbird 115
window.gTabmail.currentAbout3Pane.folderTree.focus();
```

```
// Thunderbird 102
window.SetFocusMessagePane();

// Thunderbird 115
window.gTabmail.currentAboutMessage.getMessagePaneBrowser().focus();
```

About new mail front end
http://developer.thunderbird.net/thunderbird-development/codebase-overview/mail-front-end
http://developer.thunderbird.net/add-ons/updating/tb115/adapt-to-changes-in-thunderbird-103-115

**Comment by MatthiasHGW** [comment]
Thank you very much, `window.gTabmail.currentAbout3Pane.folderTree.focus();` works perfectly!

**Comment by dantefromhell** [comment]
> How to focus other panes:
>
>// Thunderbird 102
window.SetFocusThreadPane();

>// Thunderbird 115
window.gTabmail.currentAbout3Pane.threadTree.table.body.focus();

@morat523035 
Thanks for these, they work well when viewing emails. However when I view a webpage loaded from one of my RSS feeds it triggers a reload of the page instead.

What is the correct way to make the pane switch work in email as well as RSS feed view?

**Comment by morat523035** [comment]
I cannot reproduce a message pane reload using the focus method with the Mozilla Blog feed.

```
// Focus folder pane
window.gTabmail.currentAbout3Pane.folderTree.focus();

// Focus thread pane
window.gTabmail.currentAbout3Pane.threadTree.table.body.focus();

// Focus message pane
window.gTabmail.currentAboutMessage.getMessagePaneBrowser().focus();

// Reload message pane
window.gTabmail.currentAboutMessage.getMessagePaneBrowser().reload();
```

Mozilla Blog
http://blog.mozilla.org/feed/

**Comment by dantefromhell** [comment]
Indeed I can confirm correct behaviour for the Mozilla Blog.

My feed was displaying https://github.com/NixOS/nixpkgs/commit/402663dc19c3961bf52063bb720c58087b567675 from https://github.com/NixOS/nixpkgs/commits/master/pkgs/games/factorio/versions.json.atom

Looking closer it actually didnt reload the webpage, but loaded the parent commit page, which is bound to keyboard shortcut `p` on the GitHub page. The same shortcut I have configured.

I was assuming that any keybinds for Thunderbird would not be forwarded to any content displayed. Is this not correct?
