### ISSUE TITLE
Unset "m" causes menu accelerator to fail

### ISSUE THREAD

**Issue by bgoodmansf** [wshanks/tbkeys#168]
Adding
{
   "m": "unset"
}
to the main key bindings prevents the Message menu from opening when ALT-m is pressed.

The menu opens if the ALT key is pressed and released before pressing "m" but this is not standard menu behavior.

**Comment by morat523035** [comment]
Similar issue
http://github.com/wshanks/tbkeys/issues/78

Workaround
http://github.com/wshanks/tbkeys/issues/114

**Comment by bgoodmansf** [comment]
You're correct. This is a duplicate of #78. I missed it.

I see the failure on the File, Message and Tools menus, but not on the other menus.

**Comment by bgoodmansf** [comment]
Close as duplicate of #78
