### ISSUE TITLE
How to remove default tbkeys-lite keybindings

### ISSUE THREAD

**Issue by silverqx** [wshanks/tbkeys#170]
When I remove the default o, f, a, ... keybindings in the `Main key bindings` section then they are automatically restored. How can I remove them permanently, I want to define my keybindings.

**Comment by morat523035** [comment]
Test input for main key bindings section:

```
{
  "ctrl+1": "func:toAddressBook"
}
```

```
{
  "ctrl+1": "func:toAddressBook",
  "ctrl+2": "func:openAddonsMgr"
}
```

Did you remember to click the "Save settings" button at the bottom?

**Comment by silverqx** [comment]
Of course, I remove all default bindings, currently, I have only one binding on both sections, every section contains one binding, then click save, close the addons tab, and when I reopen addons and open tbkeys-lite settings again then all default keybindings are back. 

For me it's reproducible every time on the latest Thunderbird.

**Comment by morat523035** [comment]
The addon settings work correctly for me.

tbkeys 2.2.4 (not lite version)
Thunderbird 115.12.1
Windows 10 Pro 22H2 32-bit

Try testing with all addons disabled, except the tbkeys-lite addon. Remember to restart the app.

How settings are stored
http://github.com/wshanks/tbkeys/issues/164

**Comment by silverqx** [comment]
Ok, sry, the problem was that I had a comma after the keybinding like:

```json
{
    "ctrl+shift+a": "func:openAddonsMgr",
}
```

And that was a reason why it was not saved, there is no validation so you don't know if it's saved correctly. So the problem was invalid JSON. 

Thx for your help anyway 👍

**Comment by silverqx** [comment]
And now I also see there is a validation, the textarea is red when the json is invalid, so everything is fine and totally my fault 😅

**Comment by morat523035** [comment]
Glad you got it working.

Troubleshooting tbkeys addon
http://forums.mozillazine.org/viewtopic.php?p=14872763#p14872763
