### ISSUE TITLE
The add-on is disabled on TB 128.0esr

### ISSUE THREAD

**Issue by gkarag** [wshanks/tbkeys#172]
Hello,

I updated my Thunderbird to version 128.0esr and tbkeys was one of the add-ons that was disabled. Do you plan to make it compatible?

Thanks and kind regards.

**Comment by wshanks** [comment]
Yes, I will try to update it on addons.thunderbird.net soon. I think tbkeys-lite just needs a max Thunderbird version bump. tbkeys (not lite) seems to work okay for me with TB 128 (though some functions could have changed names in Thunderbird).

**Comment by wshanks** [comment]
I updated the compatibility range on addons.thunderbird.net without uploading a new version. It seems to work for me now. Please report if you have any problems.

**Comment by gkarag** [comment]
The updated addon worked for me. Thanks a lot 🙏🏻
