### ISSUE TITLE
tbkeys captures the keyboard input in the quick filter fields in TB128.0esr

### ISSUE THREAD

**Issue by gkarag** [wshanks/tbkeys#174]
There have been similar issues with the earlier versions of Thunderbird, which eventually got fixed. Suddenly the problem appeared in the latest version again.

**Comment by wshanks** [comment]
Thanks, tbkeys is updated now and an update for tbkeys-lite was submitted to addons.thunderbird.net.

**Comment by gkarag** [comment]
I have updated the tbkeys-lite and indeed the problem looks solved. I will close the issue. Thanks a lot 🙏🏻
