### ISSUE TITLE
feature request: access to tabs API

### ISSUE THREAD

**Issue by stevenxxiu** [wshanks/tbkeys#187]
It'll be great if I could have keyboard access to tabs. I want a way to:

- Close a tab.
- Get the current tab index.
- Move a tab to some index.

Just exposing [tabs API — WebExtension Documentation for Thunderbird 128<br><br>Manifest V2 documentation](https://webextension-api.thunderbird.net/en/128-esr-mv2/tabs.html) is probably good enough.

**Comment by morat523035** [comment]
Try these:

```
// close selected tab
window.gTabmail.closeTab();
```

```
// close third tab
window.gTabmail.closeTab(2);
```

```
// show selected tab index
window.alert(window.gTabmail.currentTabInfo.tabId);
```

```
// switch second tab and third tab
window.gTabmail.moveTabTo(2, 1);
```

Reference (see "Thunderbird's tab UI mechanism" in tabmail.js)
http://searchfox.org/comm-esr128/source/mail/base/content/tabmail.js
http://searchfox.org/comm-esr128/source/mail/components/extensions/child/ext-tabs.js
http://searchfox.org/comm-esr128/source/mail/components/extensions/parent/ext-tabs.js

MailExtension API support
http://github.com/wshanks/tbkeys/issues/46

**Comment by stevenxxiu** [comment]
Thanks, that's really handy.

One issue I encountered is that I can't set keybinds starting with `t` due to the ancient bug <https://bugzilla.mozilla.org/show_bug.cgi?id=615957>, but that might not be anything *tbkeys* can do about.

**Comment by morat523035** [comment]
I can use the T and Ctrl+T key bindings in the main window.

```
{
  "t": "window.alert('example one');",
  "ctrl+t": "window.alert('example two');"
}
```

> Key bindings do not fire in text input fields unless the first key combo includes a modifier other than shift.

README - Customizing key bindings
http://github.com/wshanks/tbkeys?tab=readme-ov-file#customizing-key-bindings

> Go to Next Unread Thread (and mark current thread as read) - T keyboard shortcut

Keyboard shortcuts - Moving around Thunderbird
http://support.mozilla.org/kb/keyboard-shortcuts-thunderbird#w_moving-around-thunderbird

**Comment by stevenxxiu** [comment]
What I meant here is using a leader like key. Using `t` doesn't work. Indeed <https://github.com/wshanks/tbkeys/blob/b12a968fee9dcc9788b5e38859f8186c68c99188/README.md> says:

> Single keys with modifiers may be mapped to override the built-in shortcuts but not sequences.

My desired config for this part is:

```json
{
  // ...
  "t x": "window.gTabmail.closeTab()",
  "t X": "window.gTabmail.undoCloseTab()",
  "t m h": "window.gTabmail.moveTabTo(window.gTabmail.tabContainer.selectedIndex, window.gTabmail.tabContainer.selectedIndex - 1)",
  "t m l": "window.gTabmail.moveTabTo(window.gTabmail.tabContainer.selectedIndex, window.gTabmail.tabContainer.selectedIndex + 2)",
  // ...
}
```

However through some research, I found `t` to be defined at <https://github.com/mozilla/releases-comm-central/blob/948397baced6301276c2b8f9c35569acfda0d87b/suite/locales/en-US/chrome/mailnews/messenger.dtd#L260>. For *Arch Linux*, this file is included in `/usr/lib/thunderbird/omni.ja`.

I found [Disable keyboard shortcuts in Thunderbird - Unix & Linux Stack Exchange](https://unix.stackexchange.com/a/587424) useful. It is important to reload the cache after patching this file.

Here's my script to patch *Thunderbird* to disable `t`, for *Arch Linux*:

```sh
#!/bin/sh
tempdir="$(mktemp --directory)"
cd "${tempdir}"

unzip -qq /usr/lib/thunderbird/omni.ja \
  chrome/en-US/locale/en-US/messenger/messenger.dtd \
  chrome/messenger/content/messenger/messageWindow.xhtml \
  chrome/messenger/content/messenger/messenger.xhtml \
  -d .
sed --in-place --regexp-extended 's/<!ENTITY nextUnreadThread.key "t">/<!-- \0 -->/' \
  "chrome/en-US/locale/en-US/messenger/messenger.dtd"
sed --in-place --regexp-extended 's/<key id="key_nextUnreadThread".+\/>/<!-- \0 -->/' \
  "chrome/messenger/content/messenger/messageWindow.xhtml"
sed --in-place --regexp-extended 's/<key id="key_nextUnreadThread".+\/>/<!-- \0 -->/' \
  "chrome/messenger/content/messenger/messenger.xhtml"
zip -q -0 --update --recurse-paths /usr/lib/thunderbird/omni.ja .

cd ..
rm -rf "${tempdir}"
```

This can be added to a *Pacman* hook, so *Thunderbird* gets patched automatically on updates.
