### ISSUE TITLE
Remap F keys ?

### ISSUE THREAD

**Issue by dzlater** [wshanks/tbkeys#188]
First off - this is a terrific add-on. 
Just the ability to run filters from the keyboard is a game changer.

Is there a way to map F keys ? 
Specifically, I want to disable the message pane toggle for F8.

Thanks!

**Comment by morat523035** [comment]
Use the unset binding to unbind built-in key bindings.

```
{
  "f1": "cmd:cmd_toggleMessagePane",
  "f8": "unset"
}
```

README - Command syntax
http://github.com/wshanks/tbkeys#command-syntax

**Comment by dzlater** [comment]
Thank you - that worked perfectly!
