### ISSUE TITLE
Define key to save attachments

### ISSUE THREAD

**Issue by yringot** [wshanks/tbkeys#191]
Hi. I would like to define a key for saving all attachments of an email. I'm struggling a bit with the syntax. (I have full tbkeys installed.)

The element I'd like to trigger looks like this in DevTools:

```
<menuitem id="context-saveAttachment" label="Speichern…" accesskey="S" oncommand="HandleMultipleAttachments(this.parentNode.attachments, 'saveAs');">
    <label class="menu-text" crop="end" aria-hidden="true" value="Speichern…" accesskey="S"/>
    <hbox class="menu-accel-container" aria-hidden="true"><label class="menu-accel"/></hbox>
</menuitem>
```

What is the correct command to trigger this command? I naively tried with `window.document.getElementById('context-saveAttachment').HandleMultipleAttachments(this.parentNode.attachments, 'saveAs')` but this results in `Uncaught TypeError: window.document.getElementById(...) is null` in the console. Any help?

**Comment by morat523035** [comment]
Try this:

```
window.goDoCommand('cmd_saveAllAttachments');
```

Reference
http://searchfox.org/comm-esr128/search?q=cmd_saveAllAttachments
http://searchfox.org/comm-esr128/search?q=HandleMultipleAttachments

**Comment by yringot** [comment]
Thank you very much. It works very well.

I'm still mystified as how to arrive at this command name. The output from the window.gTabmail... command is several pages long and does not contain the string `cmd_saveAllAttachments`. The searchfox.org links were not helpful either. Anyway, I realise that TB is a large and changing code base and that it probably is futile to try and compile an exhaustive list of functions, so thank you again!

**Comment by morat523035** [comment]
Are you asking how to find the cmd_saveAllAttachments string using the Developer Toolbox utility?

Menu Bar > Message > Attachments > Save All…

The "Save All…" menuitem#menu-saveAllAttachments element uses the
command="cmd_saveAllAttachments" attribute.

Select attachments using shift key and mouse clicks > right click on a selected attachment > Save As…

The "Save As…" menuitem#context-saveAttachment element uses the
oncommand="HandleMultipleAttachments(this.parentNode.attachments, 'saveAs');" attribute.

Reference
http://searchfox.org/comm-esr128/search?q=menu-saveAllAttachments&path=xhtml
http://searchfox.org/comm-esr128/search?q=context-saveAttachment&path=xhtml

Troubleshooting and Tips
http://forums.mozillazine.org/viewtopic.php?p=14872763#p14872763

**Comment by yringot** [comment]
Oh cool I hadn't thought about using the menu bar! Now it's clear. Maybe this could be a tip to add to the wiki?
