### ISSUE TITLE
Missing single unsets?

### ISSUE THREAD

**Issue by pqmatagi** [wshanks/tbkeys#43]
First and foremost, thanks for continuing to keep this working and improve it!  (It's still amazing to me that the Mozilla guys refuse to allow these to be disabled from their UI ...) 

In MacOS, Thunderbird 68.12.0, the native single key shortcuts include the second-level menu item

* **n**     Go > Next > Unread Message

and the uppercase ones

* **C**     Message > Mark >All Read
* **J**     Message > Mark > As Not Junk

In addition, there is a top level menu item

* **K**     Message > Ignore Subthread

None of these appear to be disabled after use of the "Unset singles" button. (There are some other second level menu items, but I believe they're all overridden by your unset-singles config.)

Perhaps not as harmful as some other easily typed things, but I see no reason to leave them active if that can be avoided.

**Comment by pqmatagi** [comment]
Almost forgot: I'd strongly suggest `del` (and `backspace`) be added to the unset-singles list. On my Mac, `del` is `Edit > Delete Message`, which seems a really good one to avoid.

(I'm a terrible typist, so my TB single key mistakes often used to include one of these before I noticed anything was wrong :cursing_face: .)

**Comment by rubo77** [comment]
I think it is very unlikely that you use the del key without looking, where you are in the type context

**Comment by pqmatagi** [comment]
I have on several occasions been typing a reply, looked at a previous message for info, then continued editing my reply without noticing the focus is still in the message pane rather than the window I think I'm typing my reply in. Others may not have my problem!

But - I'm not seeing the logic in keeping that particular single key shortcut when the button gets rid of all the others. If it is indeed considered to be in the stock useful set, it should be specified explicitly, not by omitting it from the settings altogether.

**Comment by willsALMANJ** [comment]
`n`, `C`, `J`, and `K` should all be added.

With `del`, I think it can be argued either way. The question is what would most users pressing the "Unset singles" button expect to happen. One answer would be to disable all individual key presses. Another would be to disable all keys that normally are only used for text input. I think most users would consider `del` a functional key like the arrow keys, page up/down, etc. and not expect it to be unset, so I lean towards not unsetting it. It is possible for users to click "Unset singles" and then add `"del": "unset"` by hand. The documentation could also clarify that it is only the text input keys that are unset and that other keys like `del` may be unset if the user wants that.
