### ISSUE TITLE
Access rightclick menu in messagepane

### ISSUE THREAD

**Issue by yamsu** [wshanks/tbkeys#49]
Is there a way to access the rightclick menu pane and select an option in messagepane. 

I would like to have a shortcut that toggles xnote++ (another thunderbird plugin). In fact, this could open us a variety of additional use cases that accelerate routine workflow.

Further, on a separate note (no pun intended!) can we access thunderbirds menubar options and assign shortcuts.

Thanks and as always this is the indespensible thunderbird plugin.

**Comment by morat523035** [comment]
Here is the command for the xnote button on the mail toolbar.

`window.xnote.ns.Overlay.initialise('clicBouton');`

You can use the nircmd program to send a keypress to the operating system.

e.g. shift + f10 then x then c : open context menu, xnote, create note

`(function () {
  var localFile = window.Components.classes['@mozilla.org/file/local;1'].
    createInstance(window.Components.interfaces.nsIFile);
  var process = window.Components.classes['@mozilla.org/process/util;1'].
    createInstance(window.Components.interfaces.nsIProcess);
  var args = ['sendkeypress', 'shift+f10', 'x', 'c'];
  localFile.initWithPath('C:\\nircmd.exe');
  process.init(localFile);
  process.run(false, args, args.length);
})();`

http://www.nirsoft.net/utils/nircmd.html
http://www.nirsoft.net/utils/nircmd2.html#sendkeypress

**Comment by yamsu** [comment]
@morat523035 Thanks for the response, how did you find the following command, which works as expected:
`window.xnote.ns.Overlay. initialize('clicBouton');`

I'm on linux hence i can't use nircmd, which is a windows utility. Fortunately, xdotool does something similar.
But i couldn't get your function working, in the following implementation, can you give me any tips, Thanks

```
"z": "(function () {
  var localFile = window.Components.classes['@mozilla.org/file/local;1'].
    createInstance(window.Components.interfaces.nsIFile);
  var process = window.Components.classes['@mozilla.org/process/util;1'].
    createInstance(window.Components.interfaces.nsIProcess);
  var args = ['windowactivate', '$(xdotool search --name \'Inbox\' | tail -1)', 'key', 'shift+f10', 'x', 'm'];
  localFile.initWithPath('/usr/bin/xdotool');
  process.init(localFile);
  process.run(false, args, args.length);
})();",
```

The xdotool command the works from the terminal is as follows:
```
xdotool windowactivate "$(xdotool search --name 'Inbox' | tail -1)" key Shift+F10 x c
```

**Comment by morat523035** [comment]
I use the developer toolbox to find commands.

http://forums.mozillazine.org/viewtopic.php?p=14866214#p14866214
http://forums.mozillazine.org/viewtopic.php?p=14772136#p14772136

Try creating a bash file to run the xdotool command, then run the bash file in tbkeys.

If the code fails in tbkeys, then test the code in the error console.

It may be necessary to change an access key in a menu item.

http://forums.mozillazine.org/viewtopic.php?f=39&t=3066910

Tips...

http://forums.mozillazine.org/viewtopic.php?p=14872763#p14872763

**Comment by yamsu** [comment]
Thanks for all the details, perhaps you would like to put your post in the wiki. It would be really helpful for people to tinker.

The bash script idea worked, one can send any key combinations to the script as args to execute.

The function is unchanged
```(function () {var localFile = window.Components.classes['@mozilla.org/file/local;1'].
    createInstance(window.Components.interfaces.nsIFile);
  var process = window.Components.classes['@mozilla.org/process/util;1'].
    createInstance(window.Components.interfaces.nsIProcess);
  var args = [ 'Shift+F10', 'x', 'c'];
  localFile.initWithPath('/home/user/bin/tbxdoscript.sh');
  process.init(localFile);
  process.run(false, args, args.length);})();
```
tbxdoscript.sh
```
#!/usr/bin/env bash
xdotool windowactivate "$(xdotool search --name 'Inbox' | tail -1)" key $@
```
