### ISSUE TITLE
unset the Delete key shortcut?

### ISSUE THREAD

**Issue by MartyPlotkin** [wshanks/tbkeys#51]
Will, thank you!! for developing this extension and updating it to work with Tbird 78. I've been suffering ever since Dorando stopped working.

Is it possible to "unset" the out-of-the box behavior of the Delete key? I have tried spelling Delete in various ways in the mapping, but no success yet. Thanks!

-Marty

**Comment by willsALMANJ** [comment]
Hi Marty, I think `"del": "unset"` should work. There is some discussion in #43. I am pretty sure I tested that it worked back then. The key names like `del` are the ones used by Mousetrap. See the "Supported keys" section here: https://craig.is/killing/mice

**Comment by MartyPlotkin** [comment]
Very odd. I edited the 'Main key bindings' section as follows, and clicked 'Save settings'. The only one that is still operating is "del".

{
    "0": "unset",
    "1": "unset",
    "2": "unset",
    "3": "unset",
    "4": "unset",
    "5": "unset",
    "6": "unset",
    "7": "unset",
    "8": "unset",
    "9": "unset",
    "j": "unset",
    "k": "unset",
    "o": "unset",
    "f": "unset",
    "#": "unset",
    "r": "unset",
    "a": "unset",
    "x": "unset",
    "c": "unset",
    "u": "unset",
    "b": "unset",
    "m": "unset",
    "p": "unset",
    "s": "unset",
    "t": "unset",
    "w": "unset",
    "]": "unset",
    "del": "unset",
    "[": "unset"
}

**Comment by willsALMANJ** [comment]
Hmm, I checked now and `"del": 'unset"` works for me. Maybe it is system dependent? I tested with Thunderbird 78.3.1 on Linux (Fedora 32).

**Comment by MartyPlotkin** [comment]
Could be - I'm on Thunderbird 78.4.1, MacOS 10.15.7.

**Comment by glennzilla** [comment]
I have the same Mac setup (as well as a Linux setup) and had the same desire to disable the Delete key Thunderbird shortcut on both systems.  I also noticed that the above suggestion only works for Thunderbird on my Linux system.  However, I found that replacing "del" with "backspace" does the trick on my Mac.

**Comment by wshanks** [comment]
Thanks @glennzilla !

**Comment by MartyPlotkin** [comment]
Thank you, @glenzilla!
