### ISSUE TITLE
Key bindings are active in options window

### ISSUE THREAD

**Issue by piterq** [wshanks/tbkeys#53]
Key bindings are active in options window.
Because of this it's impossible to type "j" character in account configuration if you set this:
{"j": "unset"}
in main key bindings.

**Comment by wshanks** [comment]
I can't reproduce this. Can you give more details about your set up and say which text box is not allowing "j" to be typed?

**Comment by piterq** [comment]
Thunderbird 78.5.0 x64.

Add-on configuration:

![image](https://user-images.githubusercontent.com/59413148/100798393-e5de8f80-3423-11eb-8842-d9d0144d79c8.png)

In this case I can't use "j" key here:

![image](https://user-images.githubusercontent.com/59413148/100798451-f42cab80-3423-11eb-96b9-eb3047620522.png)

**Comment by wshanks** [comment]
Okay, that I can reproduce. The signature box must have a special class. tbkeys allows keys through when it detects that the focused element is a text field but to do this it compares against a set list of tags and properties.
