### ISSUE TITLE
How to bind F-keys?

### ISSUE THREAD

**Issue by cakepuller** [wshanks/tbkeys#58]
Thanks so much, Will, for creating tbkeys-lite.  Life-saver after Dorando-keyconfig.

How do I bind **Function** (F??) keys?
I tried:
 **"F11": "func:MsgBodyAllParts"**
but it didn't work.  It did the Thunderbird default "_Show or hide Today Pane_"

Using a single alphabet works though, e.g.:
 **"m": "func:MsgBodyAllParts"**

Thanks for any pointers.

Using Thunderbird 78.6; tbkeys-lite 2.1.1

**Comment by wshanks** [comment]
I think Mousetrap uses lower case `f` for the function key labels. Let me know whether or not `f11` works for you.

**Comment by cakepuller** [comment]
> 
> 
> I think Mousetrap uses lower case `f` for the function key labels. Let me know whether or not `f11` works for you.

DOH! >.<
Thanks, Will.  Lowercase "f11" did the trick.
(I didn't bother to try it at first; assumed wrongly it'd be case insensitive)

**Comment by wshanks** [comment]
No problem. I am glad it works for you. It would be nice to make the keys case insensitive but I want to keep the behavior as close to Mousetrap as possible and it doesn't work that way, and the possibility of binding upper case keys makes it complicated (can't just lower case everything).
