### ISSUE TITLE
Nostalgy compatibilty

### ISSUE THREAD

**Issue by James6M** [wshanks/tbkeys#64]
I see that the tbkeys-lite author (thank you!) is also a fan of Nostalgy.  But the two sort of conflict.  "tbkeys> unset singles" unsets the 's' (the TB star command), but Nostalgy wants 's' to be the trigger for the save process.  (Nostalgy's use is not a dangerous single-key-shortcut, because it just starts a process that can then be aborted.  However, Nostalgy's Shft-S could be considered a dangerous single-key-shortcut, for those concerned about triggering something accidentally while they intend to be typing.)

I'm not exactly sure how to best fix this.  Removing "s":"unset" from tbkeys does re-enable the Nostalgy behavior.  But those wishing to unset all singles would probably wish to tie a different key sequence to the command, and I don't know how to refer to commands of add-ons.

**Comment by James6M** [comment]
Oh, I didn't realize that Nostalgy allows setting key sequences itself.  I agree that completely solves my quandary.  The combined flexibility allows for any possible setup.
I also didn't realize that tbkeys-lite is not identical to tbkeys.  I should have read all the way to the bottom of the README!

**Comment by johnnyutahh** [comment]
fyi. Thus far in my Thunderbird v91.6.1, macOS v10.15.7 environment:

Nostalgy++ v3.2.0 and tbkeys v2.2.0 are working concurrently without issues. (_Thus far_. It's early in my testing.) My tbkeys Main prefs (Compose is null), entire listing:

```
{
    "j": "cmd:cmd_nextMsg",
    "k": "cmd:cmd_previousMsg",
    "o": "cmd:cmd_openMessage",
    "f": "cmd:cmd_forward",
    "#": "cmd:cmd_delete",
    "r": "cmd:cmd_reply",
    "a": "cmd:cmd_replyall",
    "x": "cmd:cmd_archive",
    "u": "tbkeys:closeMessageAndRefresh"
}
```
