### ISSUE TITLE
How do I find more "func:"?

### ISSUE THREAD

**Issue by nutnutwin** [wshanks/tbkeys#69]
First I must thank you for doing this **great job**
Finally I can update from v60.*(For Dorando Keyconfig)

I went through the readme, and found no list of funcs

currently I am working on 
- Focus on Folder list
  Workaround by "Focus on MessageFilter", and then "Tab"
  ↑which is not pretty
- Open Options
  Workaround by Alt+T➤O using autohotkey
  ↑just as ugly(and interfere with mouse cursor sometimes)

Thank you so much

**Comment by morat523035** [comment]
There isn't a built-in function to just focus on the folder pane.

Try these:

```
func:SwitchPaneFocus
func:openOptionsDialog
```

You can focus on the folder pane with arbitrary javascript.

```
window.document.getElementById('folderTree').focus();
```

Similar issue...

http://github.com/wshanks/tbkeys/issues/65

**Comment by nutnutwin** [comment]
Hi, Thank you for the reply
Newbie to tbkey, 
1. Do I need tbkey(non lite) to run ｢func｣?
2. seems tbkey-lite is the only one available on Mozilla Addon Search
3. If I need non-lite version I have to install from xpi file?

Thank you for your time

**Comment by morat523035** [comment]
You cannot run arbitrary javascript with tbkeys-lite.

You can use the cmd shorthand and func shorthand with tbkeys and tbkeys-lite.

Use the cmd shorthand for calling a command using the goDoCommand method.

For example, "cmd:cmd_nextMsg" is the same as "window.goDoCommand('cmd_nextMsg');".

Use the func shorthand for calling a function on the window object without a parameter.

For example, "func:MsgNewMessage" is the same as "window.MsgNewMessage();".

There is a tbkeys.xpi link on the releases page...

http://github.com/wshanks/tbkeys#install

**Comment by nutnutwin** [comment]
Really Appreciate Your Reply 

Thank you.
