### ISSUE TITLE
Question about shortcut "paste without formatting"

### ISSUE THREAD

**Issue by koopernick** [wshanks/tbkeys#75]
Hello,

First of all, thank you for your addon !

I have one question that is not an issue or a bug (sorry if this is not the proper place to do so) : I'm trying to make "ctrl+v" the default for the function "paste without formatting".

However, it seems the command "cmd_pasteNoFormatting" doesn't exist/work anymore ? 
I can't find it here => https://hg.mozilla.org/comm-central/file/tip/mail/base/content/mainCommandSet.inc.xhtml
and it's the only command I found after googling for a while.

I tried => "ctrl+v": "cmd_pasteNoFormatting"
in the addon settings but that doesn't work, nothing is happening.

![ddddd](https://user-images.githubusercontent.com/4642079/120445226-b126a300-c388-11eb-8a25-d300cf396ef2.png)

Do you have any idea / work around to make this possible ? 
I know they have the "paste without formatting" option from the right click menu, but I'm looking to make that function a shortcut.

Thank you.

**Comment by wshanks** [comment]
Can you try `"ctrl+v": "cmd:cmd_pasteNoFormatting"`? The `cmd:` indicates that tbkeys should use `goDoCommand` on the following text. It did not work for me locally, but then `Paste without formatting` is greyed out in the context menu for me, so I think I have some other issue with pasting there. I still see `cmd_pasteNoFormatting` in the Mozilla code base, but I didn't trace if this is what Thunderbird uses for its text editor: https://searchfox.org/mozilla-central/source/dom/events/ShortcutKeyDefinitions.cpp#712

**Comment by koopernick** [comment]
Awesome it's working ! 

Thank you very much !

**Comment by rsbrux** [comment]
I'm trying to use this keymapping in tbkeys-lite to get around the black on black text that I often get when I paste text from e-mail into event description fields in Thunderbird 140.12.0esr in dark mode. Unfortunately, ctrl-v still gives me black-on-black text. I have restarted Thunderbird after installing tbkeys-lite and setting up 
```
{
"ctrl+v": "cmd:cmd_pasteNoFormatting"
}
```
in "Compose key bindings".
I don't find "cmd_pasteNoFormatting" in [the main command set file](https://hg.mozilla.org/comm-central/file/tip/mail/base/content/mainCommandSet.inc.xhtml) of the Thunderbird source code. Is this why this doesn't work? The command still seems to be present in [Firefox's code](https://searchfox.org/firefox-main/source/dom/events/ShortcutKeyDefinitions.cpp#733).

**Comment by morat523035** [comment]
@rsbrux

Did you read the README page?

> There are separate fields in the preferences page for setting key bindings for the main Thunderbird window and the compose window. Key bindings do not fire in other windows.

README - Customizing key bindings
http://github.com/wshanks/tbkeys#customizing-key-bindings

The main window and compose window are supported. The event dialog is not supported.

* main window - chrome://messenger/content/messenger.xhtml
* compose window - chrome://messenger/content/messengercompose/messengercompose.xhtml
* event dialog - chrome://calendar/content/calendar-event-dialog.xhtml

Reference
http://searchfox.org/comm-central/search?q=cmd_pasteNoFormatting

**Comment by rsbrux** [comment]
Not carefully enough, evidently!
Thanks for clarifying, and sorry for missing that.

**Comment by morat523035** [comment]
@rsbrux

You can create a paste no formatting button in the event dialog using the userChromeJS extension as an alternative.

* `<profile folder>\chrome\userChrome.js`

```
/* Thunderbird userChrome.js */

// tested with Thunderbird 140 only

(function () {
  if (location == "chrome://calendar/content/calendar-event-dialog.xhtml") {
    setTimeout(function () {
      var iframe = document.getElementById("calendar-item-panel-iframe");
      var win = iframe.contentWindow;
      var XUL_NS = "http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul";
      var toolbarbutton = win.document.createElementNS(XUL_NS, "toolbarbutton");
      toolbarbutton.onclick = function (aEvent) {
        var win = aEvent.target.ownerDocument.defaultView;
        if (aEvent.button == 0) {
          win.goDoCommand("cmd_pasteNoFormatting");
        }
      };
      var props = {
        id: "__unique_identifier_pasteNoFormatting_button",
        class: "formatting-button",
     // label: "Paste No Formatting",
        tooltiptext: "Paste No Formatting",
        observes: "cmd_renderedHTMLEnabler",
        style: 'list-style-image: url("chrome://messenger/skin/icons/new/compact/paste.svg");',
      };
      for (var p in props) toolbarbutton.setAttribute(p, props[p]);
      var toolbar = win.document.getElementById("FormatToolbar");
      var smiley = win.document.getElementById("smileButtonMenu");
      toolbar.insertBefore(toolbarbutton, smiley.nextSibling);
    }, 1000);
  }
})();
```

userChromeJS by jikamens
http://addons.thunderbird.net/thunderbird/addon/986610

Instructions:

1. install userChromeJS extension
2. close email client
3. create or edit userChrome.js file in chrome folder
4. open email client

Reference
http://searchfox.org/comm-central/search?q=FormatToolbar&path=calendar-item-iframe.xhtml

More info
https://forums.mozillazine.org/viewtopic.php?p=14985386#p14985386

Other thread
https://forums.mozillazine.org/viewtopic.php?t=3140164

**Comment by morat523035** [comment]
@rsbrux

You could hack the paste command as well.

* `<profile folder>\chrome\userChrome.js`

```
/* Thunderbird userChrome.js */

(function () {
  if (location == "chrome://calendar/content/calendar-event-dialog.xhtml") {
    setTimeout(function () {
      var command = document.getElementById("cmd_paste");
      command.setAttribute("oncommand", "goDoCommand('cmd_pasteNoFormatting')");
    }, 1000);
  }
})();
```

Reference
http://searchfox.org/comm-central/search?q=goDoCommand..cmd_paste&regexp=true&path=calendar-event-dialog.xhtml
