### ISSUE TITLE
Is there a way to create a keybinding for move message to folder?

### ISSUE THREAD

**Issue by axeheadfloats** [wshanks/tbkeys#94]
I found the function [here](http://kb.mozillazine.org/Keyconfig_extension:_Thunderbird) : MsgMoveMessage and I'd love to use that to create a shortcut key to move a message to a specific folder. Is this possible? I've worked at it a while to no avail.

I'd also like to be able to navigate to a folder or filter to a specific tag. Are either of these possible?

Thanks.

**Comment by wshanks** [comment]
Do you want to bind a specific key to a specific folder or tag? You should be able to do that with the non-lite version of tbkeys by using an eval command using `MsgMoveMessage` with the target folder hardcoded like `window.MsgMoveMessage('mailbox://someone@pop.example.com/Inbox')`. This is not possible with the lite version at the moment. It shouldn't be too hard to add support for arguments for `func:` commands which the lite version could support.

You might also look into Nostalgy for this case. Historically, it provided single key bindings for moving messages and going to folders. The original developer stopped supporting it with the Thunderbird compatibility changes of the last few years. He points to two other projects on the addon page which I am not as familiar with: https://addons.thunderbird.net/en-US/thunderbird/addon/nostalgy/

**Comment by axeheadfloats** [comment]
Thank you for your reply, wshanks!
Would you mind showing me an example of the exact cmd in the Main key bindings window for this? I've not done an eval command before. Though I saw the directions for it in the readme, I would really appreciate an example.

"8": func:window.MsgMoveMessage('mailbox://someone@pop.example.com/Inbox')
?

**Comment by wshanks** [comment]
It should be just

    "8": "window.MsgMoveMessage('mailbox://someone@pop.example.com/Inbox')"

I haven't tested though so there might be a silly error. The `func:NAME` syntax is shorthand for executing `window[NAME]()`. addons.thunderbird.net does not allow addons that use `eval()` so this syntax is a workaround to allow calling functions in the `window` scope which has some simple useful functions to call. When a command in tbkeys is not prefixed with `func:`, `cmd:` or `unset`, it is passed to `eval()`. So you can put arbitrary code in there though squeezing it into the json settings gets a bit painful for a large command.

**Comment by axeheadfloats** [comment]
Thank you, Will. I'll give those a try. The address doesn't seem to be the issue in this case since I tried a local mailbox as well & still no luck. I'll look into these other items you mentioned.

Thanks again.

**Comment by reagle** [comment]
I was just looking for this and am sad to see nothing is offered here. I have problems with both Nostalgy+ ([can't save configuration edits](https://github.com/opto/nostalgy-xpi/issues/186)) and Quick Folder Key Navigation (not configurable).

tbkey works great for me, and it'd be nice to have all of my keyboard mapping in a single robust add-on.

**Comment by morat523035** [comment]
@reagle

The MsgMoveMessage function takes a nsIMsgFolder object, not a URI string.

Example
http://github.com/wshanks/tbkeys/issues/72#issuecomment-1264743390

Reference
http://searchfox.org/comm-esr102/source/mailnews/base/public/nsIMsgFolder.idl

**Comment by reagle** [comment]
Yea, I suppose the functionality to move/go/copy to an arbitrary folder would require more than a simple mapping between a key and nsIMsgFolder. It'd require some sort of selector pop-up.

**Comment by reagle** [comment]
@wshanks, as you left your message in Jan and never received a response, and new code hasn't been pushed in 16 months, I fear @kewisch has moved on from the extension.

I suppose I {move,copy,go} to about ~10 folders regularly. Does tbkeys-lite permit multi-key sequences? For example `m+r` for receipts and `m+p` for personal? I could then enjoy the benefits of tbkeys and get 80% of my {copy,go,move}.

**Comment by reagle** [comment]
I see that key sequences are supported, but I'm having trouble with the specific move command. `7` will tell me the mailbox address, which I include in the command for `8`, but it doesn't work. (`9` does work.) I'm using the latest tbkeys. (Could this issue be re-opened?)

```
{
   "7": "window.alert(window.gFolderDisplay.displayedFolder.URI);",
    "8": "window.MsgMoveMessage('mailbox://nobody@Local%20Folders/A-Bulk')",
    "9": "func:CloseTabOrWindow"
}
```

**Comment by reagle** [comment]
BTW: I just discovered an alternative move/go plugin: [mmy](https://github.com/arjanarcheologie/mmy). It doesn't copy, but it also doesn't [break context menu popups](https://github.com/kewisch/quickmove-extension/issues/78) like QuickMove. Seems to exist alongside tbkeys fine -- though I'm still interested in how to configure a move in tbkeys.

**Comment by morat523035** [comment]
@reagle

Are you using tbkey or tbkeys-lite?

You cannot run arbitrary javascript with tbkeys-lite.

You can use the cmd shorthand and func shorthand with tbkeys and tbkeys-lite.

Use the cmd shorthand for calling a command using the goDoCommand method.

For example, "cmd:cmd_nextMsg" is the same as "window.goDoCommand('cmd_nextMsg');".

Use the func shorthand for calling a function on the window object without a parameter.

For example, "func:MsgNewMessage" is the same as "window.MsgNewMessage();".

There is a tbkeys.xpi link on the releases page.

Install tbkeys
http://github.com/wshanks/tbkeys#install

**Comment by reagle** [comment]
I was trying tbkeys (full). Like others have asked, what would the exact command be for what I'm trying to do? (And am I using the correct folder name?)

**Comment by morat523035** [comment]
@reagle

The 7 shortcut is correct.

The 8 shortcut is wrong because the MsgMoveMessage function takes a nsIMsgFolder object, not a URI string.

Try running the code snippet using the error console as a test.

**Comment by reagle** [comment]
Something like this? I don't know JS and something is wrong with my json...

```
"7": "window.alert(window.gFolderDisplay.displayedFolder.URI);",
"8": "(function () {
  var targetUri = 'mailbox://nobody@Local%20Folders/A-Bulk';
  var targetFolder = window.MailUtils.getExistingFolder(targetUri);
  window.MsgMoveMessage(targetFolder);
})();"
}
```

**Comment by morat523035** [comment]
Remember to remove the newline characters in custom commands so the input is a valid JSON string.

Tips
http://forums.mozillazine.org/viewtopic.php?p=14872763#p14872763

**Comment by morat523035** [comment]
@reagle

Try using the lowercase m instead of the uppercase M. And use shift+m instead of shift+M.

Similar issue
http://github.com/wshanks/tbkeys/issues/58

I never tried a key sequence so I don't know how the feature works.

**Comment by morat523035** [comment]
Maybe you can use the select prompt as an alternative.

```
(function () {
  var folderUrls = [];
  folderUrls.push('mailbox://nobody@Local%20Folders/References/general');
  folderUrls.push('mailbox://nobody@Local%20Folders/References/jobs');
  folderUrls.push('mailbox://nobody@Local%20Folders/References/personal');
  var selectedIndex = {value: null};
  var ok = Services.prompt.select(window, 'tbkeys', 'Select folder', folderUrls, selectedIndex);
  if (ok) {
    window.gFolderTreeView.selectFolder(window.MailUtils.getExistingFolder(folderUrls[selectedIndex.value]));
  }
})();
```

**Comment by gebner** [comment]
It seems like this keybinding got broken again by Thunderbird 115.  The function `MsgMoveMessage` apparently no longer exists in the main window:

```
Uncaught TypeError: window.MsgMoveMessage is not a function
    <anonymous> jar:file:///var/home/gebner/.thunderbird/a59hpr6a.default-default/extensions/tbkeys@addons.thunderbird.net.xpi!/implementation.js line 126 > eval:1
    callback jar:file:///var/home/gebner/.thunderbird/a59hpr6a.default-default/extensions/tbkeys@addons.thunderbird.net.xpi!/implementation.js:126
    _fireCallback jar:file:///var/home/gebner/.thunderbird/a59hpr6a.default-default/extensions/tbkeys@addons.thunderbird.net.xpi!/modules/mousetrap.js:616
    _handleKey jar:file:///var/home/gebner/.thunderbird/a59hpr6a.default-default/extensions/tbkeys@addons.thunderbird.net.xpi!/modules/mousetrap.js:677
    handleKey jar:file:///var/home/gebner/.thunderbird/a59hpr6a.default-default/extensions/tbkeys@addons.thunderbird.net.xpi!/modules/mousetrap.js:1008
    _handleKeyEvent jar:file:///var/home/gebner/.thunderbird/a59hpr6a.default-default/extensions/tbkeys@addons.thunderbird.net.xpi!/modules/mousetrap.js:737
```

**Comment by morat523035** [comment]
@gebner

Try these:

```
// Thunderbird 102
window.alert(window.gFolderDisplay.displayedFolder.URI);

// Thunderbird 115
window.alert(window.gTabmail.currentAbout3Pane.gFolder.URI);
```

```
// Thunderbird 102
window.alert(window.gFolderDisplay.selectedMessage.mime2DecodedSubject);

// Thunderbird 115
window.alert(window.gTabmail.currentAboutMessage.gMessage.mime2DecodedSubject);
```

```
// Thunderbird 102, MsgCopyMessage function is similar to MsgMoveMessage function

(function () {
  var targetUri = 'mailbox://nobody@Local%20Folders/Example';
  var targetFolder = window.MailUtils.getExistingFolder(targetUri);
  window.MsgMoveMessage(targetFolder);
})();

// Thunderbird 115, cmd_copyMessage command is similar to cmd_moveMessage command

(function () {
  var targetUri = 'mailbox://nobody@Local%20Folders/Example';
  var targetFolder = window.MailUtils.getExistingFolder(targetUri);
  window.goDoCommand('cmd_moveMessage', targetFolder);
})();
```

Select folder, use setter/getter of nativeTab
http://thunderbird.topicbox.com/groups/addons/T48deff5d86abce14-M71b7848a4707dd106e82ed38

About new mail front end
http://developer.thunderbird.net/thunderbird-development/codebase-overview/mail-front-end
http://developer.thunderbird.net/add-ons/updating/tb115/adapt-to-changes-in-thunderbird-103-115

**Comment by soyjcvallejo** [comment]
> It seems like this keybinding got broken again by Thunderbird 115. The function `MsgMoveMessage` apparently no longer exists in the main window:
> 
> ```
> Uncaught TypeError: window.MsgMoveMessage is not a function
>     <anonymous> jar:file:///var/home/gebner/.thunderbird/a59hpr6a.default-default/extensions/tbkeys@addons.thunderbird.net.xpi!/implementation.js line 126 > eval:1
>     callback jar:file:///var/home/gebner/.thunderbird/a59hpr6a.default-default/extensions/tbkeys@addons.thunderbird.net.xpi!/implementation.js:126
>     _fireCallback jar:file:///var/home/gebner/.thunderbird/a59hpr6a.default-default/extensions/tbkeys@addons.thunderbird.net.xpi!/modules/mousetrap.js:616
>     _handleKey jar:file:///var/home/gebner/.thunderbird/a59hpr6a.default-default/extensions/tbkeys@addons.thunderbird.net.xpi!/modules/mousetrap.js:677
>     handleKey jar:file:///var/home/gebner/.thunderbird/a59hpr6a.default-default/extensions/tbkeys@addons.thunderbird.net.xpi!/modules/mousetrap.js:1008
>     _handleKeyEvent jar:file:///var/home/gebner/.thunderbird/a59hpr6a.default-default/extensions/tbkeys@addons.thunderbird.net.xpi!/modules/mousetrap.js:737
> ```

"shift+i": "window.goDoCommand('cmd_moveMessage', window.MailUtils.getExistingFolder('imap://jc.vallejo%40opensupport.com.bo@mail.opensupport.com.bo/INBOX'));",

**Comment by tmthyDXTR** [comment]
To move a message to a specfic folder in folder pane view with Thunderbird version 151 you have to import MailUtils like this:

`"KEYBINDING": "var { MailUtils } = ChromeUtils.importESModule('resource:///modules/MailUtils.sys.mjs'); var folder = MailUtils.getExistingFolder('imap://FOLDER_URI'); window.goDoCommand('cmd_moveMessage', folder)"`
