### ISSUE TITLE
on mac, how to use command+backspace to delete message and calendar item?

### ISSUE THREAD

**Issue by field210** [wshanks/tbkeys#97]
i tried these in `compose key bindings`, but none works.

    "command+backspace": "cmd:cmd_delete"
    "command+del": "cmd:cmd_delete"
    "cmd+backspace": "cmd:cmd_delete"
    "cmd+del": "cmd:cmd_delete"

**Comment by wshanks** [comment]
Hmm, it should be `command` and not `cmd` (also `meta` should work). I think there is a misunderstanding about the compose key bindings though. Those are only active in the compose window (when writing a new message). `cmd:cmd_delete` will delete the currently selected message in the message list. You likely wouldn't want to do that in the middle of composing a message, so I am guessing you want these bindings in the main key bindings section?

**Comment by field210** [comment]
works in main key bindings section. thanks.
