### ISSUE TITLE
How to concurrently run 'tbkeys' and 'Nostalgy++' add-ons in v91.6.x or above without key-binding collisions?

### ISSUE THREAD

**Issue by johnnyutahh** [wshanks/tbkeys#98]
https://www.reddit.com/r/Thunderbird/comments/swsu0y/how_to_concurrently_run_tbkeys_and_nostalgy/

**Comment by johnnyutahh** [comment]
Past, related discussion:
https://github.com/wshanks/tbkeys/issues/64

**Comment by wshanks** [comment]
From what you wrote in #64, it seems like it is okay to close this?
